mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_USER=school_admin
    - MYSQL_PASSWORD=admin_pwd
    - MYSQL_DATABASE=school
    - MYSQL_ROOT_PASSWORD=root
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"